export const listData = [
  { icon: "123", coinName: "Btc", price: "$0.00", balance: "0 USDC" },
  { icon: "123", coinName: "Btc", price: "$0.00", balance: "0 USDC" },
  { icon: "123", coinName: "Btc", price: "$0.00", balance: "0 USDC" },
  { icon: "123", coinName: "Btc", price: "$0.00", balance: "0 USDC" },
  { icon: "123", coinName: "Btc", price: "$0.00", balance: "0 USDC" },
  { icon: "123", coinName: "Btc", price: "$0.00", balance: "0 USDC" },
  { icon: "123", coinName: "Btc", price: "$0.00", balance: "0 USDC" },
  { icon: "123", coinName: "Btc", price: "$0.00", balance: "0 USDC" },
  { icon: "123", coinName: "Btc", price: "$0.00", balance: "0 USDC" },
  { icon: "123", coinName: "Btc", price: "$0.00", balance: "0 USDC" },
  { icon: "123", coinName: "Btc", price: "$0.00", balance: "0 USDC" },
  { icon: "123", coinName: "Btc", price: "$0.00", balance: "0 USDC" },
  { icon: "123", coinName: "Btc", price: "$0.00", balance: "0 USDC" },
  { icon: "123", coinName: "Btc", price: "$0.00", balance: "0 USDC" },
  { icon: "123", coinName: "Btc", price: "$0.00", balance: "0 USDC" },
  { icon: "123", coinName: "Btc", price: "$0.00", balance: "0 USDC" },
  { icon: "123", coinName: "Btc", price: "$0.00", balance: "0 USDC" },
  { icon: "123", coinName: "Btc", price: "$0.00", balance: "0 USDC" },
  { icon: "123", coinName: "Btc", price: "$0.00", balance: "0 USDC" },
  { icon: "123", coinName: "Btc", price: "$0.00", balance: "0 USDC" },
  { icon: "123", coinName: "Btc", price: "$0.00", balance: "0 USDC" },
  
];
